[build]
  command = "npm run setup-env && npm run build"

[build.environment]
  USER_NAME = "${process.env.NETLIFY_ENV_USER_NAME}" 
  PASSWORD = "${process.env.NETLIFY_ENV_PASSWORD }" # 
  MAP_KEY = "${process.env.NETLIFY_ENV_MAP_KEY}" #
[context.production.environment]
  USER_NAME = "$USER_NAME" 
  PASSWORD = "$PASSWORD" # 
  MAP_KEY = "$MAP_KEY" # 

[context.deploy-preview.environment]
   USER_NAME = "$USER_NAME" 
  PASSWORD = "$PASSWORD" # 
  MAP_KEY = "$MAP_KEY" # Variable Netlify que vous souhaitez utiliser pour les aperçus de déploiement

[context.branch-deploy.environment]
  USER_NAME = "$USER_NAME" 
  PASSWORD = "$PASSWORD" # 
  MAP_KEY = "$MAP_KEY"

[context.split-test.environment]
   USER_NAME = "$USER_NAME" 
  PASSWORD = "$PASSWORD" # 
  MAP_KEY = "$MAP_KEY"